server:
  image: sjoerdmulder/teamcity
  ports:
    - 8111:8111
  volumes:
    - ./teamcity-storage:/var/lib/teamcity
agent:
  image: therubble/teamcity-agent-docker
  links:
    - server
  environment:
    TEAMCITY_SERVER: http://server:8111
